### ISSUE TITLE
get_disk_size returns 0

### ISSUE THREAD

**Issue by Rob1-** [lukas2511/sky3ds.py#1]
On OSX 10.10.1, Python 3.4.2

Running the formatting operation works fine:
```python
diskutil umountDisk /dev/disk3
sudo python ./sky3ds.py -d /dev/disk3 -f -c
```
Making sure the disk is sky3ds ready:
```python
diskutil umountDisk /dev/disk3
sudo python -c "from disk import check_if_sky3ds_disk; print(check_if_sky3ds_disk('/dev/disk3'))"
True
```
Now my issue is that disk.get_disk_size() always return 0, and therefore makes the write_rom() (and all methods that depends on the disk_size) to fail.
```python
sudo python -c "from disk import get_disk_size; print(get_disk_size('/dev/disk3'))"
0
```
The layout of the disk looks fine though:
```bash
$ diskutil list
/dev/disk3
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *31.9 GB    disk3
   1:             Windows_FAT_32 NO NAME                 524.3 KB   disk3s1
```
Note that the issue is the same after a simple format of the disk using Disk Utility, get_disk_size() returns 0 no matter what.
Any suggestion on how to fix the get_disk_size, or I my missing a step somewhere?
Thanks!

**Comment by lukas2511** [comment]
Mh... currently get_disk_size uses a trick to seek to the end of the disk, and read the number of bytes that were skipped doing that. Maybe this operation doesn't work correctly on OSX. I'm going to clean up the code a bit in the next days and may look into other solutions for getting the disk-size.

**Comment by Rob1-** [comment]
I'm able to write roms to the disk by hardcoding the value returned by get_disk_size by the way.
Thanks for your help!

**Comment by lukas2511** [comment]
I changed the function a bit, can you test if the new function works on osx? I moved the code, but I guess you can figure out how to access the function.

**Comment by lukas2511** [comment]
Should be fixed by now.
