### ISSUE TITLE
Third Party Impropertly Linked

### ISSUE THREAD

**Issue by ratherDashing** [lukas2511/sky3ds.py#6]
git clone https://github.com/lukas2511/sky3ds.py.git
Cloning into 'sky3ds.py'...
remote: Counting objects: 87, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 87 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (87/87), done.
Checking connectivity... done.

 cd sky3ds.py/

 ./runtests.py
Traceback (most recent call last):
  File "./runtests.py", line 6, in <module>
    import sky3ds.test_disk
  File "/home/mwarren/tmp/sky3ds.py/sky3ds/test_disk.py", line 76, in <module>
    from sky3ds.disk import Sky3DS_Disk
  File "/home/mwarren/tmp/sky3ds.py/sky3ds/disk.py", line 11, in <module>
    from sky3ds import gamecard, titles
  File "/home/mwarren/tmp/sky3ds.py/sky3ds/titles.py", line 6, in <module>
    from appdirs import user_data_dir
ImportError: No module named 'appdirs'

 cd third_party/appdirs/

ls

it's empty

Ubuntu 14.04.  If it manually clone the utilities mentioned into those directories it seems to work.  I don't have a sky3ds yet so I can't truly test but I'm getting a N3DS on the 13th and evaluating my options.

Thanks for writing this utility for us Linux folk.

**Comment by lukas2511** [comment]
Those are submodules, you have to initialize them.

http://git-scm.com/book/de/v1/Git-Tools-Submodule

```
git submodule init
git submodule update
```

**Comment by ratherDashing** [comment]
Thanks!  You might want to add that to the README for doofuses like me!
