### ISSUE TITLE
Possible osx issue

### ISSUE THREAD

**Issue by zaflux** [lukas2511/sky3ds.py#7]
getting:

ERROR: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

After writing to my sdcard...

**Comment by zaflux** [comment]
This appears to be an issue if you write a game to index 31 (assuming 0 based index).  Which shouldn't happen as the sky3ds only supports 31 games (index 30).

**Comment by lukas2511** [comment]
Max number of slots fixed with commit ec1675314e33ed131163ea2871b068e431f8fcbb
